table fact_latest_holding
	lineageTag: 5ab201b9-bffa-491a-8598-ba003e6ee70f

	column security_key
		dataType: int64
		formatString: 0
		lineageTag: 54ea9d42-7f7c-4fbc-8bc5-da00aaa44216
		summarizeBy: none
		sourceColumn: security_key

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: double
		lineageTag: 7ab03380-de00-4d6a-9b31-86fa9af3cfd1
		summarizeBy: sum
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_held
		dataType: double
		lineageTag: 01845aa1-a3d5-4a74-a1f5-80d710f39113
		summarizeBy: sum
		sourceColumn: quantity_held

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column market_value
		dataType: double
		lineageTag: 9598ad7f-58e3-4cc1-8d88-7b6d5367b66d
		summarizeBy: sum
		sourceColumn: market_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column market_value_eur
		dataType: double
		lineageTag: 4d1ccc01-00f0-4647-a4ac-a92eb594d956
		summarizeBy: sum
		sourceColumn: market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fact_latest_holding = m
		mode: import
		source =
				let
				    Source = fact_holdings,
				    #"Grouped Rows" = Table.Group(Source, {"security_key"}, {{"latest_date", each List.Max([date_key]), type number}, {"all_rows", each _, type table [date_key=number, security_key=number, quantity_held=number, close_price=nullable number, market_value=nullable number, market_value_eur=number, cost_basis_eur=number, unrealized_pnl_eur=nullable number]}}),
				    #"Expanded all_rows" = Table.ExpandTableColumn(#"Grouped Rows", "all_rows", {"date_key", "quantity_held", "market_value", "market_value_eur"}, {"date_key", "quantity_held", "market_value", "market_value_eur"}),
				    #"Added Custom" = Table.AddColumn(#"Expanded all_rows", "validator1", each if [latest_date] = [date_key] then 1 else 0),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([validator1] = 1)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"security_key", "date_key", "quantity_held", "market_value", "market_value_eur"})
				in
				    #"Removed Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

